name: Build & Auto Release ICam4D

on:
  push:
    branches:
      - master   # Runs only when you push to main

permissions:
  contents: write


jobs:
  build-release:
    runs-on: windows-latest   # Since you’re building a Windows .NET app

    steps:
      # 1. Checkout the repo with full history (needed for tags)
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Set up .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      # 3. Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # 4. Build project in Release mode
      - name: Build project
        run: dotnet publish Imetric_Installer.sln -c Release -o build_output

      # 5. Get the latest version tag & bump version based on commit message keywords
      - name: Bump version
        id: versioning
        shell: pwsh
        run: |
          # Get latest tag or set starting version
          $latestTag = (git describe --tags --abbrev=0) 2>$null
          if (-not $latestTag) { $latestTag = "v8.1.5.0" }

          # Normalize the tag (remove v or V)
          $normalizedTag = $latestTag -replace '^[vV]', ''

          # Split into semantic version parts
          $ver = $normalizedTag.Split('.')
          $major = [int]$ver[0]
          $minor = [int]$ver[1]
          $patch = [int]$ver[2]
          $build = [int]$ver[3]

          # Check latest commit message for keywords
          $commitMessage = (git log -1 --pretty=%B)

          if ($commitMessage -match "\[minor\]") {
            $minor += 1
            $patch = 0
            $build = 0
          }
          elseif ($commitMessage -match "\[patch\]") {
            $patch += 1
            $build = 0
          }
          else {
            $build += 1
          }

          $newVersion = "$major.$minor.$patch.$build"
          echo "NEW_VERSION=$newVersion" >> $env:GITHUB_ENV



      # 6. Update Version.xml (version + URL)
      - name: Update Version.xml
        run: |
          $versionTag = "v${{ env.NEW_VERSION }}"   # Always lowercase "v" going forward
          $downloadUrl = "https://github.com/TayloJClo/Imetric-Installer/releases/download/$versionTag/ICam4DSetup.zip"

          # Update <version> and <url>
          (Get-Content Version.xml) `
            -replace '<version>.*</version>', "<version>${{ env.NEW_VERSION }}</version>" `
            -replace '<url>.*</url>', "<url>$downloadUrl</url>" `
          | Set-Content Version.xml

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add Version.xml
          git commit -m "Auto-update Version.xml to ${{ env.NEW_VERSION }}" || echo "No changes to commit"
          git push


      # 7. Zip the installer files
      - name: Zip build files
        run: Compress-Archive -Path build_output\* -DestinationPath Imetric_Installer_${{ env.NEW_VERSION }}.zip

      # 8. Create a new Git tag
      - name: Create Git tag
        run: |
          git tag v${{ env.NEW_VERSION }}
          git push origin v${{ env.NEW_VERSION }}

      # 9. Create a GitHub Release
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.NEW_VERSION }}
          name: Imetric Installer v${{ env.NEW_VERSION }}
          files: Imetric_Installer_${{ env.NEW_VERSION }}.zip
